//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karahisar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class karahisardbEntities19 : DbContext
    {
        public karahisardbEntities19()
            : base("name=karahisardbEntities19")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MusteriTablo> MusteriTablo { get; set; }
        public virtual DbSet<SepetTablo> SepetTablo { get; set; }
        public virtual DbSet<UrunTablo> UrunTablo { get; set; }
        public virtual DbSet<admin> admin { get; set; }
    }
}
