//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karahisar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriTablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusteriTablo()
        {
            this.SepetTablo = new HashSet<SepetTablo>();
        }
    
        public short musteriid { get; set; }
        public string musteriadi { get; set; }
        public string musteriemail { get; set; }
        public string musteriparola { get; set; }
        public string musteriparolatekrar { get; set; }
        public string musteritel { get; set; }
        public string musteriadres { get; set; }
        public string musterisoyadi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SepetTablo> SepetTablo { get; set; }
    }
}
