//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karahisar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SepetTablo
    {
        public short sepetid { get; set; }
        public short urunid { get; set; }
        public short musteriid { get; set; }
    
        public virtual MusteriTablo MusteriTablo { get; set; }
        public virtual UrunTablo UrunTablo { get; set; }
    }
}
