//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karahisar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunTablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UrunTablo()
        {
            this.SepetTablo = new HashSet<SepetTablo>();
        }
    
        public short urunid { get; set; }
        public string urunadi { get; set; }
        public string urunmarkaadi { get; set; }
        public string urunkucukaciklama { get; set; }
        public decimal urunfiyat { get; set; }
        public string urunmarkaresim { get; set; }
        public string urunresim { get; set; }
        public string urunnota { get; set; }
        public string urunaciklama { get; set; }
        public string urunnotaresim { get; set; }
        public string uruncinsiyet { get; set; }
        public string uruncoksatanlar { get; set; }
        public string urunyeniparfum { get; set; }
        public string uruntrendler { get; set; }
        public string urunresim2 { get; set; }
        public string urunresim3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SepetTablo> SepetTablo { get; set; }
    }
}
